/// 全量 Unicode Emoji 字符映射表
/// 使用标签 [xxx] 作为富文本语法，在渲染时替换为 emoji 字符
final Map<String, String> emojiCharMap = {
  '[smile]': '😀',
  '[grin]': '😁',
  '[joy]': '😂',
  '[rofl]': '🤣',
  '[wink]': '😉',
  '[heart_eyes]': '😍',
  '[sunglasses]': '😎',
  '[thinking]': '🤔',
  '[cry]': '😢',
  '[sob]': '😭',
  '[angry]': '😠',
  '[poop]': '💩',
  '[thumbs_up]': '👍',
  '[thumbs_down]': '👎',
  '[ok]': '👌',
  '[clap]': '👏',
  '[pray]': '🙏',
  '[fire]': '🔥',
  '[heart]': '❤️',
  '[broken_heart]': '💔',
  '[star]': '⭐',
  '[sparkles]': '✨',
  '[zap]': '⚡',
  '[boom]': '💥',
  '[eyes]': '👀',
  '[wave]': '👋',
  '[party]': '🥳',
  '[gift]': '🎁',
  '[balloon]': '🎈',
  '[cake]': '🎂',
  '[beer]': '🍺',
  '[coffee]': '☕',
  '[sun]': '☀️',
  '[moon]': '🌙',
  '[cloud]': '☁️',
  '[rain]': '🌧️',
  '[snow]': '❄️',
  '[dog]': '🐶',
  '[cat]': '🐱',
  '[unicorn]': '🦄',
  '[rocket]': '🚀',
  '[car]': '🚗',
  '[airplane]': '✈️',
  '[money]': '💰',
  '[100]': '💯',
  '[check]': '✅',
  '[x]': '❌',
  '[warning]': '⚠️',
  '[question]': '❓',
  '[exclamation]': '❗',
};

/// 表情映射表
final Map<String, String> emojiMap = {
  '[smile]': 'https://img.icons8.com/emoji/48/000000/smiling-face.png',
  '[laugh]': 'https://img.icons8.com/emoji/48/000000/grinning-face.png',
  '[wink]': 'https://img.icons8.com/emoji/48/000000/winking-face.png',
  '[sad]': 'https://img.icons8.com/emoji/48/000000/crying-face.png',
  '[angry]': 'https://img.icons8.com/emoji/48/000000/angry-face.png',
  '[cool]':
      'https://img.icons8.com/emoji/48/000000/smiling-face-with-sunglasses.png',
  '[love]':
      'https://img.icons8.com/emoji/48/000000/smiling-face-with-heart-eyes.png',
  '[kiss]': 'https://img.icons8.com/emoji/48/000000/face-blowing-a-kiss.png',
  '[heart]': 'https://img.icons8.com/emoji/48/000000/red-heart.png',
  '[broken_heart]': 'https://img.icons8.com/emoji/48/000000/broken-heart.png',
  '[fire]': 'https://img.icons8.com/emoji/48/000000/fire.png',
  '[thumbs_up]': 'https://img.icons8.com/emoji/48/000000/thumbs-up.png',
  '[thumbs_down]': 'https://img.icons8.com/emoji/48/000000/thumbs-down.png',
  '[ok_hand]': 'https://img.icons8.com/emoji/48/000000/ok-hand.png',
  '[clap]': 'https://img.icons8.com/emoji/48/000000/clapping-hands.png',
  '[star]': 'https://img.icons8.com/emoji/48/000000/star-emoji.png',
  '[moon]': 'https://img.icons8.com/emoji/48/000000/crescent-moon.png',
  '[sun]': 'https://img.icons8.com/emoji/48/000000/sun-emoji.png',
  '[rain]': 'https://img.icons8.com/emoji/48/000000/cloud-with-rain.png',
  '[snow]': 'https://img.icons8.com/emoji/48/000000/cloud-with-snow.png',
  '[dog]': 'https://img.icons8.com/emoji/48/000000/dog-emoji.png',
  '[cat]': 'https://img.icons8.com/emoji/48/000000/cat-emoji.png',
  '[gift]': 'https://img.icons8.com/emoji/48/000000/gift.png',
  '[party]': 'https://img.icons8.com/emoji/48/000000/party-popper.png',
  '[coffee]': 'https://img.icons8.com/emoji/48/000000/hot-beverage.png',
  '[cake]': 'https://img.icons8.com/emoji/48/000000/birthday-cake.png'
};
